export const procedures = [
    { title: "Harmonização Facial", description: "" },
    { title: "Preenchimento Facial e Labial", description: "" },
    { title: "Lifting com fios de PDO", description: "" },
    { title: "Aplicação de Toxinas Botulínicas tipo A", description: "" },
    { title: "Ultrassom Microfocado Hifu", description: "" },
    { title: "Skinbooster", description: "" },
    { title: "Intradermoterapia avançada", description: "" },
    { title: "Tratamento de vasinhos e varizes(Peim)", description: "" },
    { title: "Lipoenzimatica", description: "" },
    { title: "Bioestimuladores", description: "" },
    { title: "Sculptra", description: "" },
    { title: "Radiesse", description: "" },
    { title: "Ellansé", description: "" },
    { title: "Tratamento para estrias com Striort e mesoterapia", description: "" },
    { title: "Lifting com Jato de Plasma", description: "" },
    { title: "Blefaroplastia sem cortes", description: "" },
    { title: "Depilação a laser com Priscila Gouvea", description: "" },
    { title: "Tratamento para flacidez corporal ", description: "" },
    { title: "Tratamento para Celulites", description: "" },
    { title: "Tratamento Capilar", description: "" },
    { title: "Lipo de papada sem cortes", description: "" },
    { title: "Microtox", description: "" },
    { title: "Hidrolipoclasia Vibratória", description: "" },
    { title: "Peeling Diamond Despigmentante", description: "" },
    { title: "Peeling de Renovação", description: "" },
    { title: "Peeling de Diamante", description: "" },
    { title: "Peeling ácido retinóico", description: "" },
    { title: "Massagens com a profissional Massoterapeuta Walquiria Brito", description: "" },
    { title: "Massagem modeladora", description: "" },
    { title: "Massagem para dor e relaxante", description: "" },
    { title: "Lipocavitação", description: "" },
    { title: "Radiofrequência", description: "" },
    { title: "Cavitação", description: "" },
    { title: "Endermoterapia", description: "" },
    { title: "Pump Up para o bumbum", description: "" },
    { title: "Criolipolise", description: "" },
    { title: "Ventosaterapia", description: "" },
    { title: "Massagem para dor com pedras vulcânicas", description: "" },
    { title: "Drenagem linfática", description: "" },
    { title: "Drenagem pós operatório", description: "" },
]